{% set data = load_setup_py_data() %}

package:
  name: pycaret
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pandas
    - numpy
    - seaborn
    - matplotlib
    - ipython
    - joblib
    - scikit-learn
    - shap
    - ipywidgets
    - yellowbrick
    - xgboost
    - lightgbm
    - plotly
    - wordcloud
    - textblob
    - cufflinks-py
    - umap-learn
    - pyLDAvis
    - gensim
    - spacy
    - nltk
    - mlxtend
    - pyod
    - catboost
    - pandas-profiling
    - kmodes
    - datefinder
    - datetime
    - awscli

  run:
    - python
    - pandas
    - numpy
    - seaborn
    - matplotlib
    - ipython
    - joblib
    - scikit-learn
    - shap
    - ipywidgets
    - yellowbrick
    - xgboost
    - lightgbm
    - plotly
    - wordcloud
    - textblob
    - cufflinks-py
    - umap-learn
    - pyLDAvis
    - gensim
    - spacy
    - nltk
    - mlxtend
    - pyod
    - catboost
    - pandas-profiling
    - kmodes
    - datefinder
    - datetime
    - awscli

test:
  imports:
    - pycaret

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
